### ISSUE TITLE
How stable is this?

### ISSUE THREAD

**Issue by JustinDrake** [libp2p/js-libp2p-webrtc-direct#13]
I'm potentially interested in using WebRTC in production. Is this transport usable?

**Comment by daviddias** [comment]
It is stable till the best capacity of the WebRTC shim you use for Node.js :) Have you tried it yet?

**Comment by daviddias** [comment]
More info on how to plug other transports (including libp2p-webrtc-star) at the new examples section in libp2p/examples - https://github.com/libp2p/js-libp2p/tree/master/examples

Closing this issue, let me know if you have any other question.
