### ISSUE TITLE
[QUESTION] What is listening on port 9090

### ISSUE THREAD

**Issue by educob** [libp2p/js-libp2p-webrtc-direct#137]
Hi.

I tried to connect the libp2p node in the browser to my nodejs libp2p node running on my backend but I got an error:
`TypeError: Cannot destructure property 'upgrader' of 'undefined' as it is undefined.`

What is running in port 9090 in the example?

How can I connect the libp2p on the browser to a libp2p node in nodejs?

Thanks.

**Comment by vasco-santos** [comment]
Hello @educob 

This example should be helpful for you https://github.com/libp2p/js-libp2p/tree/master/examples/webrtc-direct

**Comment by educob** [comment]
Hi. thanks for answering.

I'll try to run it.

Cheers.

**Comment by educob** [comment]
It worked!!!

Thanks.
