### ISSUE TITLE
support for https

### ISSUE THREAD

**Issue by sethhrbek** [libp2p/js-libp2p-webrtc-direct#177]
When connecting from broswer -> nodeJS libp2p nodes, getting a `Mixed Content` error in chrome. 

I believe this is due to the `onSignal` method in `index.ts`:

```
        const url = `http://${host}:${cOpts.port}`
        const path = `/?signal=${base58btc.encode(fromString(signalStr))}`
        const uri = url + path
```

Does http need to be hard-coded, or could an option for `https` be added?

**Comment by mpetrunic** [comment]
@sethhrbek Would you mind opening up PR to make it configurable?
