### ISSUE TITLE
createListener: options ignored

### ISSUE THREAD

**Issue by backkem** [libp2p/js-libp2p-webrtc-direct#20]
It seems the options argument is ignored in createListener. It is overwritten on index.js#L103. Is there a reason for this? If not, I suggest we use the same technique used on index.js#L31 to disable trickle-ice but pass the options along.
I can create a PR if we come to an agreement.

**Comment by vasco-santos** [comment]
Hello @backkem 

I do not see any reason for this, so it seems to be a bug. It would be nice if you create a PR for solving this, as well as adding a test 🙂

**Comment by backkem** [comment]
Created a PR without a test. I'm honestly not sure how add tests for this change. I may be able to with some pointers but my JavaScript is too limited to come up with one myself.

Some context: I'm interacting with this transport since I'm trying to build ``go-libp2p-webrtc-direct`` based on [pions/webrtc](https://github.com/pions/webrtc).
